markdown        : kramdown
kramdown        :
  entity_output : as_input # &mdash; is output as &mdash;
  smart_quotes  : [39, 39, 34, 34] # decimal for left/right single/double quotes
exclude         : [branding, "*.Rmd"]
contact         : "admin@software-carpentry.org"
github_url      : "https://github.com/swcarpentry"
irc_url         : "irc://moznet/sciencelab"
rss_url         : "http://software-carpentry.org/feed.xml"
swc_prefix      : "http://software-carpentry.org"
twitter_name    : "@swcarpentry"
twitter_url     : "https://twitter.com/swcarpentry"
windows_installer_path : "http://files.software-carpentry.org/SWCarpentryInstaller.exe"
vm_url          : "https://docs.google.com/uc?id=0B4Kr6DYkzkQtd05FekRId05DLXM&amp;export=download"
lesson_repo     : "https://github.com/jrherr/2015-01-27-msu_icer"
lesson_site     : "http://jrherr.github.io/2015-01-27-msu_icer"
